### ISSUE TITLE
create 'blueprint' feature

### ISSUE THREAD

**Issue by deebloo** [DannyBlueDesign/angular-blueprint#4]
give the opportunity to override generators by having a blueprints folder.

**Comment by mhoffmeyerDC** [comment]
Do you have any examples handy of this blueprint stuff in use? I poked around google some but wasn't really sure what I was looking at.

**Comment by deebloo** [comment]
this will probably have to wait until the generators have been build. Take a look at the ember cli documentation to see what I am talking about

**Comment by mhoffmeyerDC** [comment]
Ooof. I just did. ಠ_ಠ I'm confused.

**Comment by deebloo** [comment]
http://www.ember-cli.com/#generators-and-blueprints

**Comment by deebloo** [comment]
https://github.com/DannyBlueDesign/generator-angular-blueprint
